### ISSUE TITLE
installed but not showing up as a provider in strapi admin

### ISSUE THREAD

**Issue by negati-ve** [floreabogdan/strapi-upload-minio#1]
Installed the plugin using 
`npm install --save strapi-upload-minio-unofficial`

Navigated to http://localhost:1337/admin/plugins/upload/configurations/development

Minio provider doesn't show up in the list of providers

**Comment by floreabogdan** [comment]
Hi, sorry, I somehow missed this issue. I'll have a look these days but you should probably check the forks, maybe they got it working.

**Comment by floreabogdan** [comment]
According to strapi docs I did the following:
* in project root:
```
mkdir providers && cd providers
git clone https://github.com/floreabogdan/strapi-upload-minio.git
```
edit `providers/strapi-upload-minio/package.json` and `change "name" from "strapi-upload-minio-unofficial" to "strapi-provider-upload-minio"`

now in project root edit package.json and add the following manual dependency:
`"strapi-provider-upload-minio": "file:providers/strapi-upload-minio"`

run `npm i --save`

edit or create `./config/plugins.js`:
```
module.exports = ({ env }) => ({
    upload: {
      provider: 'minio',
      providerOptions: {
        public: 'Q3AM3UQ867SPQQA43P2F',
        private: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',
        endpoint: 'https://play.minio.io:9000',
        bucket: 'mintest',
      },
    }
  });
```

**Comment by floreabogdan** [comment]
forgot to mention: it seems that it no longer has an admin page for configuration... it just works if configured correctly in config/plugins.js
